### ISSUE TITLE
 release notaryproject-1.0.0-draft.1 as part of alpha-1 milestone

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#108]
Proposing we release notaryproject-v1.0.0-draft.1 as we have completed the milestone. Release process is defined here.

High level deliverables as as follows:

- [x]  Decide on main commit for release
- [x]  Cut branch named v1.0.0-draft.1 based on agreed upon main commit
- [x] Cut a tag named v1.0.0-draft.1
- [x]  Update README.md

/cc @SteveLasker @NiazFK @justincormack @sajayantony

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release.

**Comment by iamsamirzon** [comment]
Closing this issue.  The system level release notes are at https://github.com/notaryproject/roadmap/blob/main/RELEASENOTES/v2.0.0.alpha-1.MD, and I will update the README.MD file in the roadmap repo as part of alpha-2 release.
