### ISSUE TITLE
release notaryproject-1.0.0-draft.2 as part of alpha-2 milestone

### ISSUE THREAD

**Issue by iamsamirzon** [notaryproject/specifications#138]
Proposing we release notaryproject-v1.0.0-draft.2 as we have completed the alpha-2 milestone. Release process is defined here. 

High level deliverables as as follows:

- [x]  Decide on main commit for release
- [x]  Cut branch named v1.0.0-draft.2 based on agreed upon main commit
- [x]  Cut a tag named v1.0.0-draft.2 
- [x]  Update README.md 
- [x] [Generate release notes for this repo](https://github.com/notaryproject/notaryproject/releases/tag/v1.0.0-draft2)
- [x] [Generate system release notes NV2](https://github.com/notaryproject/roadmap/blob/iamsamirzon-patch-5/RELEASENOTES/v2.0.0.alpha-2.MD)

/cc @SteveLasker @NiazFK @justincormack @sajayantony

Can the maintainers please respond with a +1 comment once you are in favor of cutting this release. This release defines the specifications required for implementers to work on Notation client and Notation libraries for the next milestone.

**Comment by sajayantony** [comment]
LGTM  /cc @shizhMSFT

**Comment by sajayantony** [comment]
Candidate commit - [656f08a](https://github.com/notaryproject/notaryproject/commit/656f08a69d5e10564857467d95302e446e1883d1)
