### ISSUE TITLE
Notary v2: Prototype 2 Scope

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/specifications#53]
To support [Notary v2 requirements](https://github.com/notaryproject/requirements#goals) for multiple signatures that don't change the artifact digest or tag, we must support new artifacts that link to existing artifacts.

## Goals & Intent

With [Prototype-1]() complete, we must now harden the linked artifacts implementation with a spec and design that could be deployed for production validation. While the design will be prototyped in CNCF Distribution, the full implementation will not be completed in CNCF Distribution. Cloud providers have cloud-optimized implementations, and implementers of CNCF Distribution have their unique product implementations. The purpose of the prototype is to prove the APIs are capable of being implemented.

The prototype should:

- [x] 1. Implement the [oci.artifact.manifest spec](https://github.com/opencontainers/artifacts/pull/29), supporting linked manifests in [CNCF distribution](https://github.com/notaryproject/distribution/tree/prototype-2).
- [x] 2. Implement the [oci.artifact.manifest links API](https://github.com/opencontainers/artifacts/pull/29), supporting retrieving linked manifests in CNCF distribution.
- [x] 3. Implement [ORAS client](https://github.com/notaryproject/oras/tree/prototype-2) libraries, enabling the pushing of the `oci.artifact.manifest` with the link, discovering and pulling of artifacts, using the [OCI.artifact.manifest](https://github.com/opencontainers/artifacts/pull/29)
- [ ] 4. ~~ORAS cli to support pushing by digest, enabling the ability to update an existing tag, after the updated image and signatures have been posted.~~ _(needs further refactoring not related to notary efforts)_
- [x] 5. Converge docker-generate and docker-nv2 into the nv2 repo. Update the [nv2 cli](https://github.com/notaryproject/nv2/tree/prototype-2) to create a docker plug-in to provide `docker sign, verify push, pull` capabilities, supporting the `oci.artifact.manifest` and linked manifest discovery.
- [x] 6. Incorporate any [nv2](https://github.com/notaryproject/nv2/tree/prototype-2) client feedback items related to signing and verifying. (TBD)
- [ ] 7. ~~With ORAS support, users should be able to link Notary v2 signatures or other files, including SBoM simulated files. ORAS push, would push the single file reference as a tar file, eliminating the `org.opencontainers.image.title` annotation.~~ See [oras issue # 114](https://github.com/deislabs/oras/issues/114) _(needs further refactoring not related to notary efforts)_
- [ ] 8. ~~Update the [docker-generate](https://github.com/notaryproject/docker-generate/tree/prototype-2) plug-in to support pushing the image by digest, the linked signature, then pushing the tag update.~~ _(needs further refactoring not related to notary efforts)_
- [ ] 9. Implement an OPA/Gatekeeper policy that confirms signature validation, before deploying an image to k8s.

The prototype should not:

1. Attempt to complete the CNCF distribution implementation with de-duping or garbage collection. Linked storage layout will be completed, enabling CNCF distribution implementors to complete their specific implementations.
2. Focus on private or public key acquisition. Key management is not part of this prototype.

## Target Experience

The experience should focus on the e2e tooling, including the use of the docker cli.

[Demo Script](https://github.com/notaryproject/nv2/blob/prototype-2/docs/nv2/demo-script-detailed.md)

## Deliverables

- [x] Instance of cncf distribution to locally run. The prototype would be checked into: [notaryproject/distribution/prototype-2](https://github.com/notaryproject/distribution/tree/prototype-2).

2. A built image, users can run locally pushed to: [docker.io/notaryv2/registry:nv2-prototype-2](https://hub.docker.com/u/notaryv2)
3. A docker plug-in to simulate the docker build, sign, push experience
4. An OPA/Gatekeeper policy for validating signatures, prior to image deployment

**Comment by dlorenc** [comment]
@sajayantony thanks, I agree. Clarifying exactly what threat model this prototype is intended to address would be useful. I'm still lost on the purpose of the self-signed certificate.

**Comment by SteveLasker** [comment]
> The prototype should not:
> - Focus on private or public key acquisition. Key management is not part of this prototype.

**Comment by SteveLasker** [comment]
Mostly finished wtih prototype-2

- [x] [nv2 updates](https://github.com/notaryproject/nv2/pull/53) _pending PR review_
- [x] [CNCF Distribution support for reference types](https://github.com/notaryproject/distribution/tree/prototype-2)
- [x] [CNCF Distribution persistence docs](https://github.com/notaryproject/distribution/pull/9)  _pending PR review_
- [x] [ORAS Experimental Validation](https://github.com/deislabs/oras/blob/prototype-2/docs/artifact-manifest.md)
- [ ] OPA/Gatekeeper validation

**Comment by SteveLasker** [comment]
House cleaning as prototype-2 has been complete for a while, and we're working on the [alpha1](https://github.com/notaryproject/notaryproject/milestone/9) release
